In [1]:
import numpy as np
import tensorflow as tf

from IPython.display import Image

![](https://github.com/StrixzIV/01416417-deep-learning-and-application/blob/main/assets/1-1-fig1.jpg?raw=true)

In [2]:
xy = np.loadtxt('../data/data-01-test-score.csv', delimiter = ',', dtype = np.float32)
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.]], dtype=float32)

In [3]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data)
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]]
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [4]:
x_test = np.array([[100, 70, 101]], dtype = np.float32)
x_test

array([[100.,  70., 101.]], dtype=float32)

Defining model

In [5]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=(3,))
])

model

/Users/jikaewsi/miniforge3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<Sequential name=sequential, built=True>

Compiling model

In [6]:
LEARNING_RATE = 1e-2

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),
    loss='mean_squared_error'
)

Training model

In [7]:
N_ITERATIONS = 2000

history = model.fit(x_data, y_data, epochs=N_ITERATIONS)
print("Training complete! Final Loss:", history.history['loss'][-1])

Epoch 1/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 469ms/step - loss: 94668.7812
Epoch 2/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 93174.4609
Epoch 3/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 91692.3203
Epoch 4/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 90222.6016
Epoch 5/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 88765.5078
Epoch 6/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 87321.2188
Epoch 7/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 85889.9141
Epoch 8/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 84471.7812
Epoch 9/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 83066.9922
Epoch 10/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 81675.7109
Epoch 11/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 80298.0938
Epoch 12/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 78934.2891
Epoch 13/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 77584.4297
Epoch 14/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 76248.6641
Epoch 15/2000


Model architecture summary

In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14 (60.00 B)

 Trainable params: 4 (16.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 10 (44.00 B)

Model's internal parameters (weight, bias)

In [9]:
weights = model.get_weights()
print(f'Weight: {weights[0]}, Bias: {weights[1]}')

Weight: [[0.4205494 ]
 [0.75216854]
 [0.81906307]], Bias: [1.2372584]


Model's prediction on test data

In [10]:
y_pred = model.predict(x_test)
print(f'Predicted score: {y_pred[0][0]}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Predicted score: 178.66937255859375
